---
- hosts: all
  vars:

  tasks:
    - include_tasks: "tasks/set_fact.yml"

    - stat:
        path: "{{ BUILD_DIR }}/{{ DRUPAL_DOCROOT }}./docksal"
      register: docksal

    - name: Restart docksal container with fin up
      shell: source ~/.zshrc && fin up
      when: docksal.stat.exists
      args:
        executable: /bin/zsh
        chdir: "{{ BUILD_DIR }}"

    - name: "Include site status check"
      include_tasks: "tasks/check-site-status.yml"

    - name: Show install path
      debug:
        msg: "Install to {{ BUILD_DIR }}"

    - name: Show npm install path
      debug:
        msg: "NPM install in {{ NPM_INSTALL_PATHS }}"

    - include_tasks: "tasks/npm-install-direct.yml"
      when: NPM_INSTALL_PATHS != 'auto'

    - include_tasks: "tasks/npm-install.yml"
      when: NPM_INSTALL_PATHS == 'auto'

    - include_tasks: "tasks/composer-install.yml"

    - name: "Check if directory exists"
      file: "path={{ BUILD_DIR }} state=directory"

    - name: "Include backup tasks"
      include_tasks: "tasks/backup-site.yml"
      when: drupal_check == true and DRUPAL_MAX_BACKUP_FILES > 0

    - name: "Sync local host to remote"
      synchronize:
        archive: yes
        src: "{{ CI_PROJECT_DIR }}/"
        dest: "{{ BUILD_DIR }}"
        delete: true
        rsync_opts:
          - "--exclude-from=/excludes.txt"

    - name: Add docksal.env file
      template:
        src: ../templates/docksal.env.j2
        dest: "{{ DOCKSAL_ENV_FILE }}"
        force: true

    - name: Restart docksal container with fin up
      shell: source ~/.zshrc && fin up
      args:
        executable: /bin/zsh
        chdir: "{{ BUILD_DIR }}"

    - name: "Include site installation"
      include_tasks: "tasks/install-site.yml"
      when: drupal_check != true

    - name: "Migration"
      include_tasks: "tasks/migrate-site.yml"
      when: drupal_check == true

    - include_tasks: "tasks/update-site.yml"
      when: drupal_check == true

    - include_tasks: "tasks/features-site.yml"
      when: DRUPAL_FEATURE_REVERT is defined

    - name: Clear drupal cache
      shell: source ~/.zshrc && fin drush cr
      args:
        executable: /bin/zsh
        chdir: "{{ BUILD_DIR }}/{{ DRUPAL_DOCROOT }}"
      ignore_errors: yes