---
- name: "Check backup directory exists"
  file: "path={{ BUILD_DIR }}/../backups state=directory"

- name: "Check how many backups exists"
  shell: ls -ltc
  args:
    chdir: "{{ BUILD_DIR }}/../backups"
    executable: /bin/zsh
  register: files

- name: "Check how many backups exists"
  shell: "fin drush mysql-dump > ../../backups/backup-{{ CI_COMMIT_REF_NAME }}-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.sql"
  args:
    chdir: "{{ BUILD_DIR }}/{{ DRUPAL_DOCROOT }}"
    executable: /bin/zsh
