---
- name: "Check backup directory exists"
  file:
    path: "{{ BACKUP_DIR }}/"
    state: directory

- name: "Check how many backups exists"
  shell: "fin drush sql-dump > {{ BACKUP_DIR }}/backup-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.sql"
  args:
    chdir: "{{ BUILD_DIR }}/{{ DRUPAL_DOCROOT }}"
    executable: /bin/zsh

- find: path="{{ BACKUP_DIR }}"
  register: backup_files

- set_fact:
    diff: "{{ (backup_files.files|list|length|int) - (DRUPAL_MAX_BACKUP_FILES|int)}}"

- file:
    state: absent
    path: "{{ item }}"
  when: diff > 1
  with_items: "{{ (backup_files.files | sort(attribute='ctime') | map(attribute='path') | list  | list)[:(diff|int)] }}"