---
- name: "Check backup directory exists"
  file:
    path: "{{ BACKUP_DIR }}/"
    state: directory

- name: "Check how many backups exists"
  shell: "fin drush sql-dump > {{ BACKUP_DIR }}/backup-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.sql"
  args:
    chdir: "{{ BUILD_DIR }}/{{ DRUPAL_DOCROOT }}"
    executable: /bin/zsh

- find: path="{{ BACKUP_DIR }}"
  register: backup_files

- set_fact:
    max_files: 5
    num_files: "{{ backup_files.files|list|length|int }}"

- set_fact:
    diff: "{{ (num_files|int) - (max_files|int) }}"

- shell: "rm -rf {{ item }}"
  when: (num_files|int) > (max_files|int)
  with_items: "{{ (backup_files.files | sort(attribute='ctime') | map(attribute='path') | list  | list)[:(diff|int)] }}"