---
- name: Install local composer.
  local_action:
    shell: "composer install {{ COMPOSER_INSTALL_FLAGS }}"
    args:
      chdir: "{{ CI_PROJECT_DIR }}/{{ DRUPAL_DOCROOT }}"
      executable: /bin/zsh
