---
- name: Check if feature module is installed
  shell: fin drush pm-list --status=enabled | grep "(features)"
  args:
    chdir: "{{ BUILD_DIR }}/{{ DRUPAL_DOCROOT }}"
    executable: /bin/zsh
  register: drupal_features_installed
  ignore_errors: yes

- name: Revert features
  shell: fin drush fia -y
  args:
    chdir: "{{ BUILD_DIR }}/{{ DRUPAL_DOCROOT }}"
    executable: /bin/zsh
  when: drupal_features_installed.stdout != ""