---
- name: Show message
  debug:
    msg: "Install drupal with profile {{ DRUPAL_PROFILE }} and flags {{ DRUPAL_SITE_INSTALL_FLAGS }}"
- name: Install drupal site.
  shell: "source ~/.zshrc && fin drush si {{ DRUPAL_PROFILE }} {{ DRUPAL_SITE_INSTALL_FLAGS }} --db-url=mysql://root:root@db/drupal -y"
  args:
    chdir: "{{ BUILD_DIR }}/docroot"
    executable: /bin/zsh