---
- name: Found all npm packages.
  local_action: "cd {{ CI_PROJECT_DIR }}/{{ DRUPAL_DOCROOT }} && find {{ CI_PROJECT_DIR }}/{{ DRUPAL_DOCROOT }} -iname "package.json" -type f -printf '%h'"
  register: npm_paths

- name: Start webpack
  local_action: "cd {{ item }} && npm install && npm build:dev"
  with_items: {{ npm_paths }}
