---
- name: Find all npm packages
  local_action:
    module: find
    patterns: 'package.json'
    paths: "{{ CI_PROJECT_DIR }}"
    recurse: true
  register: npm_paths
  when: NPM_INSTALL_PATHS == 'auto'
  ignore_errors: yes

- name: Start webpack in npm paths
  local_action: "shell cd {{ item.path | dirname }} && npm install --quiet && npm start"
  with_items: "{{ npm_paths.files | list }}"
  when: NPM_INSTALL_PATHS == 'auto'
  ignore_errors: yes
