---
- name: Find all npm packages
  local_action:
    module: find
    patterns: 'package.json'
    paths: "{{ CI_PROJECT_DIR }}"
    recurse: true
  register: npm_paths

- debug:
    msg: "{{ npm_paths }}"

- name: Start webpack
  local_action: "shell cd {{ item.path | dirname }} && npm install && npm start"
  with_items: "{{ npm_paths.files | list }}"
  when: npm_paths is defined
