---
- set_fact:
    CI_ENVIRONMENT_URL: "{{ lookup('env','CI_ENVIRONMENT_URL') | default('test.dev.b-connect.eu', true) }}"
    CI_PROJECT_NAMESPACE: "{{ lookup('env','CI_PROJECT_NAMESPACE') | default('test-dev', true) }}"
    CI_PROJECT_NAME: "{{ lookup('env','CI_PROJECT_NAME') | default('test-dev', true) }}"
    CI_ENVIRONMENT_SLUG: "{{ lookup('env','CI_ENVIRONMENT_SLUG') | default('dev', true) }}"
    CI_REPOSITORY_URL: "{{ lookup('env','CI_REPOSITORY_URL') | default('dev', true) }}"
    CI_PROJECT_DIR: "{{ lookup('env','CI_PROJECT_DIR') | default('/builds/gitlab-org/gitlab-ce', true) }}"
    CI_COMMIT_REF_NAME: "{{ lookup('env','CI_COMMIT_REF_NAME') }}"
    CI_COMMIT_REF_SLUG: "{{ lookup('env','CI_COMMIT_REF_SLUG') }}"
- set_fact:
    BUILD_DIR: "/home/{{ ansible_user }}/ansible/{{ CI_PROJECT_NAMESPACE}}/{{ CI_PROJECT_NAME }}/{{ CI_ENVIRONMENT_SLUG }}"
    BACKUP_DIR: "/home/{{ ansible_user }}/ansible/backups/{{ CI_PROJECT_NAMESPACE}}/{{ CI_PROJECT_NAME }}/{{ CI_ENVIRONMENT_SLUG }}"
- set_fact:
    COMPOSER_INSTALL_FLAGS: "{{ lookup('env','COMPOSER_INSTALL_FLAGS') | default('', true) }}"
- set_fact:
    DOCKSAL_ENV_FILE: "{{ BUILD_DIR }}/.docksal/docksal-local.env"
    DOCKSAL_ADD_VIRTUAL_HOSTS: "{{ lookup('env','DOCKSAL_ADD_VIRTUAL_HOSTS')| default(false, true)  }}"
- set_fact:
    DRUPAL_SITE_INSTALL_FLAGS: "{{ lookup('env','DRUPAL_SITE_INSTALL_FLAGS') | default('', true) }}"
    DRUPAL_SITE_CONFIG: "{{ lookup('env','DRUPAL_SITE_CONFIG') | default(false, true) }}"
    DRUPAL_PROFILE: "{{ lookup('env','DRUPAL_PROFILE') | default('standard', true) }}"
    DRUPAL_ACCOUNT_NAME: "{{ lookup('env','DRUPAL_ACCOUNT_NAME') | default('admin', true) }}"
    DRUPAL_ACCOUNT_PASS: "{{ lookup('env','DRUPAL_ACCOUNT_PASS') | default('admin', true) }}"
    DRUPAL_DOCROOT: "{{ lookup('env','DRUPAL_DOCROOT') | default('docroot', true) }}"
    DRUPAL_FEATURE_REVERT: "{{ lookup('env','DRUPAL_FEATURE_REVERT') }}"
    DRUPAL_MAX_BACKUP_FILES: "{{ lookup('env','DRUPAL_MAX_BACKUP_FILES') | default(3, true) }}"
    DRUPAL_INSTALLED: false
    drupal_check: false
    VIRTUAL_HOST: "{{ CI_ENVIRONMENT_URL }}"
    DRUPAL_MIGRATE_FILES: "{{ lookup('env','DRUPAL_MIGRATE_FILES') | default(false, true) }}"
    DRUPAL_MIGRATE_DB: "{{ lookup('env','DRUPAL_MIGRATE_DB') | default(false, true) }}"
- set_fact:
    VIRTUAL_HOST: "{{ VIRTUAL_HOST }}{% if DOCKSAL_ADD_VIRTUAL_HOSTS != false %},{{ DOCKSAL_ADD_VIRTUAL_HOSTS }}{% endif %}"
    when: DOCKSAL_ADD_VIRTUAL_HOSTS is defined