---
- name: Import configs
  shell: "fin drush cim -y"
  when: DRUPAL_SITE_CONFIG != false
  args:
    chdir: "{{ BUILD_DIR }}/{{ DRUPAL_DOCROOT }}"

- name: Update db
  shell: "fin drush updatedb --entity-updates -y"
  args:
    chdir: "{{ BUILD_DIR }}/{{ DRUPAL_DOCROOT }}"
